name: CI

on:
  workflow_dispatch:
  pull_request:
  schedule:
    # NOTE: We run this weekly at 1 am UTC on every Saturday
    - cron:  '0 1 * * 6'

jobs:
  # This is mirrored in the release workflow.
  build_and_test:
    runs-on: ubuntu-latest
    name: 'Build and Test / Python ${{ matrix.python-version-short }}'
    strategy:
      matrix:
        include:
          - python-version-short: "3.6"
            python-version: 3.6.13
    steps:
      - name: test gha
        shell: bash
        run: |
          echo ${{ matrix.python-version-short }}
          echo ${{ matrix.python-version-short[0] }}
          echo ${{ matrix.python-version-short }} | jq '.[0]'
